services:
  app:
    build: .
    container_name: flask-production
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: shop
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    container_name: mysql-production
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shop
